### ISSUE TITLE
sam内部的groundingdino和segment在github中下载的代码里无法引用

### ISSUE THREAD

**Issue by bissotow** [Meng-Sang/SA-DNet#1]

**Comment by Meng-Sang** [comment]
能提供下具体的错误吗？

**Comment by bissotow** [comment]
你好。我在下载了groundingdino之后把groundingdino项目添加进SA-DNet，但是这段初始化出错
from groundingdino.util.inference import load_model, load_image, predict, annotate
from groundingdino.util import box_ops




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Meng-Sang/SA-DNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月6日(星期三) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Meng-Sang/SA-DNet] sam内部的groundingdino和segment在github中下载的代码里无法引用 (Issue #1)





 
能提供下具体的错误吗？

**Comment by bissotow** [comment]
关于包的位置问题已经解决，但是出现了一个模型的错误，在model中的reg文件夹下MatchFormer中的weight的model.ckpt使用torch.load报错。

并且这个错误，导致了main函数无法运行。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Meng-Sang/SA-DNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月6日(星期三) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Meng-Sang/SA-DNet] sam内部的groundingdino和segment在github中下载的代码里无法引用 (Issue #1)





 
能提供下具体的错误吗？

**Comment by Meng-Sang** [comment]
提问前，请给出报错的截图或者具体错误信息！如果可以的话尽量给出复现的环境，以便定位问题的存在！
