### ISSUE TITLE
在加载SA-DNet-master/model/reg/MatchFormer/weights/model.ckpt的时候，报错_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by bissotow** [Meng-Sang/SA-DNet#2]
在加载SA-DNet-master/model/reg/MatchFormer/weights/model.ckpt的时候，报错_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Meng-Sang** [comment]
请检查模型是否下载完整！可以参考如下链接：https://github.com/thu-coai/CDial-GPT/issues/94#issuecomment-1220251363

**Comment by bissotow** [comment]
感谢您的时间！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Meng-Sang/SA-DNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月6日(星期三) 晚上8:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Meng-Sang/SA-DNet] 在加载SA-DNet-master/model/reg/MatchFormer/weights/model.ckpt的时候，报错_pickle.UnpicklingError: invalid load key, 'v'. (Issue #2)





 
请检查模型是否下载完整！可以参考如下链接：thu-coai/CDial-GPT#94 (comment)
